language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t jdanailov/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jdanailov/react-test npm test

after_success:
    - docker build -t jdanailov/multi-client ./client
    - docker build -t jdanailov/multi-nginx ./nginx
    - docker build -t jdanailov/multi-server ./server
    - docker build -t jdanailov/multi-worker ./worker

    # Log in the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push jdanailov/multi-client
    - docker push jdanailov/multi-nginx
    - docker push jdanailov/multi-server
    - docker push jdanailov/multi-worker
